const { Router } = require('express')
const healthController = require('../controllers/healthController')
const authRoutes = require('./auth.routes')
const contentRoutes = require('./content.routes')
const donationRoutes = require('./donations.routes')
const blogRoutes = require('./blog.routes')
const programRoutes = require('./programs.routes')
const bankAccountRoutes = require('./bankAccounts.routes')
const donationTypeRoutes = require('./donationTypes.routes')
const teamMemberRoutes = require('./teamMembers.routes')
const uploadRoutes = require('./uploads.routes')
const docRoutes = require('./doc.routes')
const donorInfoRoutes = require('./donorInfo.routes')
const contactPageRoutes = require('./contactPage.routes')
const contactMessageRoutes = require('./contactMessages.routes')

const router = Router()

router.get('/health', healthController.check)
router.use('/auth', authRoutes)
router.use('/content', contentRoutes)
router.use('/donations', donationRoutes)
router.use('/blog', blogRoutes)
router.use('/programs', programRoutes)
router.use('/bank-accounts', bankAccountRoutes)
router.use('/donation-types', donationTypeRoutes)
router.use('/team', teamMemberRoutes)
router.use('/uploads', uploadRoutes)
router.use('/doc-videos', docRoutes.videos)
router.use('/doc-photos', docRoutes.photos)
router.use('/donor-info', donorInfoRoutes)
router.use('/contact', contactPageRoutes)
router.use('/contact-messages', contactMessageRoutes)

module.exports = router
